services:
  - type: web
    name: survival-fps-v1
    runtime: node
    plan: free
    buildCommand: npm install --omit=dev
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
